update to yaml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,13 +17,21 @@ jobs:
         uses: webfactory/ssh-agent@v0.5.3
         with:
           ssh-private-key: ${{ secrets.A2HOSTING_SSH_KEY }}
-          
+
       - name: Debug SSH Connection
         run: |
           echo "Testing SSH connection..."
           ssh -vvv manders1@manders-jones.eu 'echo "SSH connection established."'
+          if [ $? -ne 0 ]; then
+            echo "Failed to establish SSH connection."
+            exit 1
+          fi
 
       - name: Deploy to A2 Hosting
         run: |
           echo "Starting deployment..."
           ssh -vvv manders1@manders-jones.eu 'cd ~/node_apps/braintrain/my-app && git pull origin master && git add . && git commit -m "Web host in sync" && git push origin master'
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed."
+            exit 1
+          fi
